name:                doc
version:             0.1.0.0
license:             BSD3
author:              "Josh Chia"
maintainer:          "joshchia@gmail.com"
copyright:           "Copyright (c) 2017 Joshua Chia"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Project for generating local haddock & hoogle
category:            Development

description:         Please see the README

library:
  source-dirs: src

dependencies:
- base >= 4.7 && < 5
- accelerate
#- accelerate-io
#- accelerate-llvm
#- accelerate-llvm-native
#- accelerate-llvm-ptx
- aeson
- aeson-pretty
- amazonka
- amazonka-core
- amazonka-s3
- array
- async
- attoparsec
- bifunctors
- bimap
- binary
- binary-conduit
- brick
- bv
- bytestring
- bytestring-conversion
- bzlib-conduit
- cassava
- cassava-conduit
- checkers
- choice
- classy-prelude
- conduit
- conduit-combinators
- conduit-extra
- containers
- contravariant
- convertible
- cpython
- criterion
- cryptonite
- csp
- data-binary-ieee754
- data-default
- data-msgpack
- data-ordlist
- Decimal
- dhall
- direct-sqlite
- directory
- distributed-closure
- enummapset
- either
- errors
- extensible
- extra
- fgl
- file-embed
- formatting
- generic-lens
- generics-sop
- ghc
- gnuplot
- graphviz
- groom
- gtk3
- hashable
- hedis
- HList
- hmatrix
- hmatrix-gsl-stats
- hourglass
- hspec
- ini
- inline-c
- inline-c-cpp
- interpolate
- io-streams
- labels
- lens
- lens-aeson
- logging-effect
#- llvm-hs
#- llvm-hs-pure
- lzma-conduit
- machines
- math-functions
- megaparsec
- microlens-platform
- MissingH
- mmap
- monad-loops
- mono-traversable
- mtl
- mustache
- mysql-haskell
- network
- network-house
- opaleye
- optparse-applicative
- optparse-generic
- parallel-io
- path
- path-io
- pcap
- pem
- polysemy
- process
- protolude
- QuickCheck
- random
- raw-strings-qq
- reactive-banana
- resourcet
- safe-exceptions
- sbv
- scientific
- scotty
- semigroups
- shelly
- singletons
- split
- sqlite-simple
- statistics
- store
- store-core
- streaming
- streaming-bytestring
- streaming-commons
- streaming-conduit
- string-conversions
- template-haskell
- temporary
- text
- text-show
- th-printf
- these
- time
- transformers
- tuple
- tuple-th
- type-level-sets
- uniplate
- unix
- unix-bytestring
- unordered-containers
- vector
- vector-algorithms
- vector-sized
- vector-th-unbox
- vinyl
- websockets
- wreq
- x509
- xmonad
- xmonad-contrib
- xmonad-extras
- zip
