name:                doc
version:             0.1.0.0
license:             BSD3
author:              "Josh Chia"
maintainer:          "joshchia@gmail.com"
copyright:           "Copyright (c) 2017 Joshua Chia"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Project for generating local haddock & hoogle
category:            Development

description:         Please see the README

library:
  source-dirs: src

dependencies:
- base
- accelerate
- accelerate-llvm
- aeson
- aeson-pretty
- amazonka
- amazonka-core
- amazonka-s3
- array
- async
- async-pool
- attoparsec
- bifunctors
- bimap
- binary
- binary-conduit
- bitvec
- brick
- bv
- bytestring
- bytestring-conversion
- bz2
- bzlib-conduit
- cassava
- cassava-conduit
- checkers
- choice
- clash-lib
- clash-prelude
- classy-prelude
- conduit
- conduit-combinators
- conduit-extra
- containers
- contravariant
- convertible
- criterion
- cryptonite
- csp
- data-binary-ieee754
- data-default
- data-msgpack
- data-ordlist
- Decimal
- dhall
- direct-sqlite
- directory
- distributed-closure
- dunai
- enummapset
- either
- elerea
- errors
- extensible
- extra
- fgl
- file-embed
- foldl
- FontyFruity
- formatting
- freer-simple
- generic-lens
- generics-sop
- genvalidity
- ghc
- gi-gtk
- gi-gtk-hs
- gloss
- gloss-rendering
- gnuplot
- graphviz
- groom
- hashable
- hedis
- HList
- hmatrix
- hmatrix-gsl-stats
- hourglass
- hspec
- ini
- inline-c
- inline-c-cpp
- interpolate
- io-streams
- JuicyPixels
- lens
- lens-aeson
- llvm-hs
- llvm-hs-pure
- lzma
- lzma-conduit
- machines
- math-functions
- megaparsec
- microlens-platform
- MissingH
- mmap
- monad-loops
- mono-traversable
- mtl
- mustache
- mysql-haskell
- network
- network-house
- opaleye
- optparse-applicative
- optparse-generic
- parallel-io
- path
- path-io
- pcap
- pem
- polysemy
- pretty-show
- process
- proto-lens
- proto-lens-protobuf-types
- protolude
- QuickCheck
- random
- random-fu
- Rasterific
- raw-strings-qq
- resourcet
- rio
- safe-exceptions
- sbv
- scientific
- scotty
- sdl2
- sdl2-gfx
- sdl2-image
- sdl2-mixer
- sdl2-ttf
- selda
- selda-postgresql
- selda-sqlite
- semigroups
- shelly
- singletons
- split
- sqlite-simple
- statistics
- store
- store-core
- streaming
- streaming-bytestring
- streaming-commons
- string-conversions
- string-interpolate
- template-haskell
- temporary
- text
- text-show
- th-printf
- these
- time
- transformers
- tuple
- tuple-th
- uniplate
- unix
- unix-bytestring
- unordered-containers
- vector
- vector-algorithms
- vector-sized
- vector-th-unbox
- vinyl
- websockets
- wreq
- x509
- xmonad
- xmonad-contrib
- xmonad-extras
- zip
