name:                doc
version:             0.1.0.0
license:             BSD3
author:              "Josh Chia"
maintainer:          "joshchia@gmail.com"
copyright:           "Copyright (c) 2017 Joshua Chia"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Project for generating local haddock & hoogle
category:            Development

description:         Please see the README

library:
  source-dirs: src

dependencies:
- base
- aeson
- aeson-pretty
- amazonka
- amazonka-core
- amazonka-s3
- array
- async
- async-pool
- attoparsec
- avro
- barbies
- bech32
- bifunctors
- bimap
- binary
- binary-conduit
- bitvec
- brick
- broadcast-chan
- bv
- bytestring
- bytestring-conversion
- bz2
- bzlib-conduit
- can-i-haz
- cassava
- cereal
- checkers
- choice
- classy-prelude
- clock
- conduit
- conduit-algorithms
- conduit-extra
- config-ini
- containers
- contravariant
- convertible
- criterion
- cryptonite
- csp
- data-binary-ieee754
- data-default
- data-interval
- data-msgpack
- data-ordlist
- Decimal
- dhall
- direct-sqlite
- directory
- distributed-closure
- enummapset
- either
- elerea
- elf
- errors
- extensible
- extra
- fgl
- file-embed
- flat
- foldl
- FontyFruity
- formatting
- generic-functor
- generic-lens
- generic-monoid
- generic-optics
- generics-sop
- genvalidity
- ghc
- gi-gtk
- gi-gtk-hs
- gloss
- gloss-rendering
- gnuplot
- graphviz
- groom
- hashable
- hasql
- hasql-pool
- hasql-transaction
- hdf5
- hedgehog
- hedis
- hmatrix
- hmatrix-gsl-stats
- hourglass
- hspec
- ini
- inline-c
- inline-c-cpp
- interpolate
- io-streams
- JuicyPixels
- lens
- lens-aeson
- lzma
- machines
- math-functions
- megaparsec
- mersenne-random
- mersenne-random-pure64
- microlens-platform
- MissingH
- mmap
- monad-loops
- mono-traversable
- monomer
- mtl
- mustache
- mwc-random
- mysql-haskell
- mysql-simple
- network
- network-house
- opaleye
- optics
- optics-core
- optparse-applicative
- optparse-generic
- parallel-io
- path
- path-io
- pcap
- pem
- polysemy
- pontarius-xmpp
- postgresql-simple
- pretty-show
- process
- prometheus
- prometheus-client
- proto-lens
- proto-lens-protobuf-types
- QuickCheck
- random
- random-fu
- Rasterific
- raw-strings-qq
- reactive-banana
- resourcet
- rio
- safe-exceptions
- sbv
- scientific
- scotty
- sdl2
- sdl2-gfx
- sdl2-image
- sdl2-mixer
- sdl2-ttf
- selections
- selective
- semigroups
- servant
- servant-client
- servant-client-core
- shelly
- singletons
- split
- sqlite-simple
- statistics
- store
- store-core
- streaming
- streaming-bytestring
- streaming-commons
- streaming-conduit
- streaming-lzma
- string-conversions
- string-interpolate
- tasty
- tasty-hedgehog
- tasty-hspec
- tasty-hunit
- tasty-quickcheck
- tasty-smallcheck
- template-haskell
- temporary
- text
- text-display
- text-show
- th-printf
- these
- time
- transformers
- tuple
- tuple-th
- uniplate
- unix
- unix-bytestring
- unordered-containers
- validity
- vector
- vector-algorithms
- vector-sized
- vector-th-unbox
- vinyl
- websockets
- witch
- wreq
- wuss
- x509
- xmonad
- xmonad-contrib
- Yampa
- zip
