name:                doc
version:             0.1.0.0
license:             BSD3
author:              "Josh Chia"
maintainer:          "joshchia@gmail.com"
copyright:           "Copyright (c) 2017 Joshua Chia"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Project for generating local haddock & hoogle
category:            Development

description:         Please see the README

library:
  source-dirs: src

dependencies:
- base >= 4.7 && < 5
- mtl
