resolver: https://raw.githubusercontent.com/jchia/stack-resolvers/master/23-20241221.yaml

packages:
- .

ghc-options:
  amazonka-s3: -XDuplicateRecordFields
  amazonka-sso: -XDuplicateRecordFields
  amazonka-sts: -XDuplicateRecordFields

flags: {}

extra-deps: []

extra-package-dbs: []
