resolver: https://raw.githubusercontent.com/jchia/stack-resolvers/master/24-20250729.yaml

packages:
- .

ghc-options:
  amazonka-s3: -XDuplicateRecordFields
  amazonka-sso: -XDuplicateRecordFields
  amazonka-sts: -XDuplicateRecordFields

flags: {}

extra-deps: []

extra-package-dbs: []

allow-newer: true

allow-newer-deps:
- amazonka-core
- hdf5
- nanovg
- universum
